import { Sour_Gummy } from "next/font/google";
import "./globals.css";

const sourGummySans = Sour_Gummy({
  variable: "--font-sour-gummy",
  subsets: ["latin"],
});

export const metadata = {
  title: "Zod + React Hook Form + Next.JS + Javascript",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${sourGummySans.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
